[profile.default]
src = "contracts"
out = "build"
libs = ["node_modules"]
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "@keep-network/=node_modules/@keep-network/",
    "@threshold-network/=node_modules/@threshold-network/"
]
solc_version = "0.8.17"
optimizer = true
optimizer_runs = 200
